-- MySQL Script generated by MySQL Workbench
-- Sun Jan 22 16:11:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TimeTracker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TimeTracker` ;

-- -----------------------------------------------------
-- Schema TimeTracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TimeTracker` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `TimeTracker` ;

-- -----------------------------------------------------
-- Table `TimeTracker`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`users` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TimeTracker`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TimeTracker`.`colections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`colections` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TimeTracker`.`colections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `update_time` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TimeTracker`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`projects` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TimeTracker`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `colections_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  PRIMARY KEY (`id`, `colections_id`),
  INDEX `fk_projects_colections1_idx` (`colections_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_colections1`
    FOREIGN KEY (`colections_id`)
    REFERENCES `TimeTracker`.`colections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TimeTracker`.`time_clocks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`time_clocks` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TimeTracker`.`time_clocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `start_time` DATETIME NOT NULL,
  `finish_time` DATETIME NULL,
  `isFinish` BIT NOT NULL DEFAULT 0,
  `old_start_time` DATETIME NOT NULL,
  `old_finish_time` DATETIME NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_time_clocks_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_time_clocks_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `TimeTracker`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TimeTracker`.`users_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`users_has_projects` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TimeTracker`.`users_has_projects` (
  `users_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  `projects_colections_id` INT NOT NULL,
  `create_time` TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  `update_time` TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
  PRIMARY KEY (`users_id`, `projects_id`, `projects_colections_id`),
  INDEX `fk_users_has_projects_projects1_idx` (`projects_id` ASC, `projects_colections_id` ASC) VISIBLE,
  INDEX `fk_users_has_projects_users1_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `update_time_UNIQUE` (`update_time` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_projects_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `TimeTracker`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_projects_projects1`
    FOREIGN KEY (`projects_id` , `projects_colections_id`)
    REFERENCES `TimeTracker`.`projects` (`id` , `colections_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TimeTracker`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TimeTracker`.`timestamps` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TimeTracker`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
