"use client";
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {Provider} from "react-redux";
import {store} from "@/Slice/store";
import {BrowserRouter, Route, Routes} from "react-router-dom";
import React from "react";
import {WeekList} from "@/Home/weekList";

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Provider store={store}>
            <BrowserRouter>
                <Routes>
                    <Route path="/" element={<WeekList />} />
                </Routes>
            </BrowserRouter>
        </Provider>

    );
}
